dist: focal

services:
  - docker

before_script:
  - mkdir -p ~/.docker/cli-plugins
  - wget -O - https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64 > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use --name mybuilder

script:
  - if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
    docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD};
    travis_wait 40 docker buildx build --platform linux/amd64,linux/arm64 -t odidev/keyval-resource:release-$TRAVIS_TAG -t odidev/keyval-resource:latest --push . 2> /dev/null;
    fi
